### ISSUE TITLE
contextmanagers.atomic_open_for_write assumes chmod never fails

### ISSUE THREAD

**Issue by GPHemsley** [sarugaku/vistir#110]
`contextmanagers.atomic_open_for_write` assumes chmod never fails, and so does not guard against possible exceptions:
https://github.com/sarugaku/vistir/blob/1bb1a6a9069b4e073554f6dae60d2bf634cf9b35/src/vistir/contextmanagers.py#L236-L237

Thus, when an exception is thrown, as it is when `chmod` is not allowed in a directory, the temporary file is left behind and the exception is propagated to the caller.

`PermissionError`, or perhaps `OSError`, should be caught and dealt with (or ignored) here.

**Comment by techalchemy** [comment]
Thanks for the report! To clarify -- you have creation permissions, but you can't `chmod` a file you created? Do you have ownership of that file or is it group delegated?

To help me understand a bit more of what is happening here, you are able to modify files in the directory but not change their modes or attributes? Can you delete them? What do you suggest as a solution here? I'm not sure about the constraints on your system but it's possible we could avoid the `chmod` call if we simply made sure to write the file with the correct permissions in the first place (i.e. via `os.umask`). I'll follow up with a branch for you to try out in a bit

**Comment by GPHemsley** [comment]
The files are present on an NTFS disk mount and the permissions are set at the mount/group level. Thus, I believe all attempts to change permissions/attributes will fail. However, read and write work fine (as do, I assume, any other direct file operations).

In my case, simply ignoring the exception that is thrown would work fine, as the file would still get created and be writable, but I don't know if that's applicable to all situations where such an exception could be thrown.

Either way, it's also important to (attempt to) clean up the temporary file if/when an exception is thrown.

**Comment by techalchemy** [comment]
Great, thanks for the context, I'm not too clear on how windows manages this but I'll add exception handling as you mention for now
