### ISSUE TITLE
ModuleNotFoundError: No module named 'vistir.compat'

### ISSUE THREAD

**Issue by krishnasism** [sarugaku/vistir#134]
Hello,
I have vistir latest version installed through pip, but when I try to do 
`from vistir.compat import Path`

I get the error
`ModuleNotFoundError: No module named 'vistir.compat'`

Are you aware of this issue?

Python Version: 3.7.9

**Comment by krishnasism** [comment]
Surprisingly when I install `0.6.1`, it works. So something up with the latest release?

**Comment by matteius** [comment]
Since Python 2 and 3.6 support ended a while ago -- the relevant compat methods have been removed.   Since you are on Python 3.7, those compat methods exist within the libraries provided by Python.

**Comment by krishnasism** [comment]
So a lot of builds will fail I believe. This library depends on your library:
https://github.com/Madoshakalaka/pipenv-setup

We downgraded vistir to 0.6.1 for now to keep our pipelines running

**Comment by matteius** [comment]
CC @oz123

**Comment by oz123** [comment]
Hi, I was risking a break without warnings. However, you should know that this removed module was for supporting pyhon2.7-python3.5. All the functionality that was removed is found in the normal standard library.

```
from vistir.compat import Path
```
Just do;
```
from pathlib import Path
```

**Comment by iuriguilherme** [comment]
What about `from vistir.compat import fs_decode` which I assume is now _os.fsdecode_?

Is there an easy list we can search for  references in the standard library?

**Comment by oz123** [comment]
Yes. That's it.

I can only recommend to look at the code of the removed module and see what it does.
Also, there were references inside vistir for this module. Check how I replaced the usage inside the latest commits.
