### ISSUE TITLE
Fix `WindowsError` code path for non-windows machines

### ISSUE THREAD

**Issue by techalchemy** [sarugaku/vistir#18]
- Subclass `OSError` or `RuntimeError`?

**Comment by techalchemy** [comment]
ref: pypa/pipenv#3017

**Comment by techalchemy** [comment]
ref: pypa/pipenv#3017

**Comment by ArtemGordinsky** [comment]
In case it’s of any use, I was only getting this error on Mac OS. Just tried on Ubuntu 18.04 and didn’t see any issues using the same version of `pipenv`.

**Comment by edsu** [comment]
Seems related to this as well? https://github.com/pypa/pipenv/issues/3017
