### ISSUE TITLE
backports.functools_lru_cache required on Python 3.4

### ISSUE THREAD

**Issue by jayvdb** [sarugaku/vistir#63]
https://github.com/sarugaku/vistir/commit/4085f78fc42fbb53160aad170d5ab33d45492797 very explicitly made `backports.functools_lru_cache` necessary for python_version <= "3.4", in the dependency info and in the import guards.

I cant see a reason why py3.4 environments cant use the system lib version.

**Comment by techalchemy** [comment]
No reason indeed
